languageCode = "en"
languageName = "English"
weight = 1

title = "illlustr"
copyright = ""

[params]
  isoCode = "en"
  displayName = "EN"
  rtl = false

  dateFormat = "2 January 2006"

  #mainSections = ["section1", "section2"]
  description = "Lukman Hakim website"

[author]
  name = "illlustr"
  image = "images/lll_avatar.png"
  headline = "Technical Artist"
  bio = "Art, Music, Software, And Games Creator."
  links = [
  #   { email = "mailto:still.lkmn@hotmail.com" },
  #   { link = "https://naiive.web.app/" },
  #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #   { apple = "https://www.apple.com" },
  #   { blogger = "https://username.blogspot.com/" },
  #   { codepen = "https://codepen.io/username" },
  #   { dev = "https://dev.to/username" },
  #   { discord = "https://discord.com/users/363734150827737098" },
  #   { dribbble = "https://dribbble.com/username" },
  #   { facebook = "https://facebook.com/username" },
  #   { flickr = "https://www.flickr.com/photos/username/" },
  #   { foursquare = "https://codepen.io/username" },
      { github = "https://github.com/illlustr" },
  #   { gitlab = "https://gitlab.com/username" },
  #   { google = "https://www.google.com/" },
      { itch-io = "https://illl.itch.io" },
  #   { hashnode = "https://username.hashnode.dev" },
      { instagram = "https://instagram.com/lkmn_in" },
  #   { keybase = "https://keybase.io/username" },
  #   { kickstarter = "https://www.kickstarter.com/profile/username" },
  #   { lastfm = "https://lastfm.com/user/username" },
  #   { linkedin = "https://linkedin.com/in/username" },
  #   { mastodon = "https://mastodon.instance/@username" },
  #   { medium = "https://medium.com/username" },
  #   { microsoft = "https://www.microsoft.com/" },
  #   { orcid = "https://orcid.org/userid" },
  #   { patreon = "https://www.patreon.com/username" },
  #   { pinterest = "https://pinterest.com/username" },
  #   { reddit = "https://reddit.com/user/username" },
  #   { researchgate = "https://www.researchgate.net/profile/username" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
      { soundcloud = "https://soundcloud.com/notlkmn" },
  #   { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  #   { steam = "https://steamcommunity.com/profiles/userid" },
  #   { telegram = "https://t.me/username" },
  #   { tiktok = "https://tiktok.com/@username" },
  #   { tumblr = "https://username.tumblr.com" },
  #   { twitch = "https://twitch.tv/username" },
  #   { twitter = "https://twitter.com/username" },
  #   { whatsapp = "https://wa.me/+62881024815075" },
  #   { youtube = "https://youtube.com/username" },
   ]
